### ISSUE TITLE
Authenticator home page is loaded in second tab after switching the experimental toggle

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#431] opened 2018-11-28 02:07 UTC
1- Launch the browser
2- Open a new tab
3- click in the address bar text to set the focus in the textbox
4- switch the toggle for enabling the experimental APIs

After the tabs are refreshed, the tabs are swapped:
![screenshot from 2018-11-27 23-00-03](https://user-images.githubusercontent.com/442821/49123882-0ace2400-f299-11e8-8d8e-03435dcdb06e.png)

It seems it's not reproducible 100% of the time.

**Comment by hunterlester** [comment] 2018-12-28 22:16
Removing from progress as I'm unable to reproduce as of https://github.com/maidsafe/safe_browser/commit/3b43db6e0ea4eb5d50d4e8a451a5cfb95e899f21.
Awaiting confirmation or different set of steps of reproduce.

**Comment by manavbp** [comment] 2019-05-14 06:14
this was fixed in #766

**Closed by manavbp** 2019-05-14 06:14 UTC
Labels: bug

**Comment by safesurfer** [comment] 2019-05-29 12:25
QA verified
