### ISSUE TITLE
Intermittent error: Packaged version of browser doesn't load and getting `Something went wrong` error, needed to package it again

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#812] opened 2019-05-30 10:16 UTC
Packaged version of the browser both prod and dev, sometimes, throw the following error, and I'm not able to load the browser at all, even after restarting it. It needs to be packaged again.

![image](https://user-images.githubusercontent.com/27578024/58626417-6635a900-82f2-11e9-8bfd-c7f6c226b674.png)

STR: (though it is an intermittent error)
1. `yarn`
2. `yarn package`

But I'm not seeing this error, when I run the browser using `yarn prod-dev` or `yarn mock-dev`

**Comment by manavbp** [comment] 2019-06-05 07:25
Closing as it is a duplicate of  #809

**Closed by manavbp** 2019-06-05 07:25 UTC

**Comment by safesurfer** [comment] 2019-06-05 07:49
This issue is referred to an issue already on the board #809 , moving it to Done.
