### ISSUE TITLE
Account setup secret and password are confused by pasted values

### ISSUE THREAD

**Issue by memcaf** [maidsafe/safe_browser#281] opened 2018-07-22 00:25 UTC
Operation System and Version: Windows 10 64bit
SAFE Browser Version: 0.10.2
Network: Testnet
Description: Pasting generated password gives "needs to be stronger" message
Steps to reproduce: Click on the account secret field. Paste a generated password value into the field. Error message "Account secret needs to be stronger."  This is even true if the password is a 100 character long random combination of upper lower numeric & symbol.   It appears that a single actual keystroke in the field solves the problem. This happens only on the account setup routine.  Once you have successfully set up the account, you can paste to login with no trouble.

**Comment by joshuef** [comment] 2018-08-14 08:35
@memcaf are you able to reproduce this with Peruse (as opposed to safe browser), using this build, eg: https://github.com/joshuef/peruse/releases/tag/webIdBrowserPOC

(as we're moving towards replacing safe_browser with peruse).

**Comment by bochaco** [comment] 2018-08-17 18:35
There are more details of the actual problem in this specific post: https://safenetforum.org/t/account-secret-needs-to-be-stronger/24627/12, it seems the issue is just when pasting the string the validation doesn't get the new value until a key type event is triggered.

**Closed** 2018-09-13 11:50 UTC
Labels: bug
