### ISSUE TITLE
Authenticating and xdg-open

### ISSUE THREAD

**Issue by b-zee** [maidsafe/safe_browser#570] opened 2019-02-01 14:35 UTC
Due to a bug in `xdg-open` a registered protocol scheme like `safe-alphachars01234` won't be opened correctly due to the digits in there. https://bugs.freedesktop.org/show_bug.cgi?id=104973

Also, because the desktop entry files containing quoted values in the `Exec` key --- like `Exec="/usr/bin/safe-browser" %u` --- `xdg-open` won't be able to open the browser binary. (https://askubuntu.com/q/189822)

Also see this topic on SAFE Dev Forum about users encountering the issue: https://forum.safedev.org/t/app-webfetch-is-not-a-function-with-safe-browser-built-from-source/2301

**Comment by joshuef** [comment] 2019-02-07 10:26
Nice research @b-zee.

We could (potentially) negate the xdg issue with `opn` perhaps (as that ships with its own), assuming that's up to date... 

Coupled with the string escaping this might solve a few xdg type issues 👍

**Comment by hunterlester** [comment] 2019-04-18 19:22
I'm using `xdg-open` v1.1.2, which I see does not include the most recent [commit](https://cgit.freedesktop.org/xdg/xdg-utils/commit/?id=bfcefa162b1dcd6d62e193019969ff2f5ff331cf) to support digits in uri scheme regex.
Why am I not able to reproduce the issue?
I'm able to `xdg-open` on `safe-bmv0lm1hawrzywzllnnhzmutynjvd3nlcg`, which does include digits.

**Comment by hunterlester** [comment] 2019-04-18 20:06
@b-zee 
> Also, because the desktop entry files containing quoted values in the Exec key --- like Exec="/usr/bin/safe-browser" %u --- xdg-open won't be able to open the browser binary.

Under what conditions though are you seeing an error?

Is `Exec="browser/node_modules/electron/dist/electron" "/home/hunterlester/safe/browser/app/main.prod.js" %u` giving you issues?

**Comment by b-zee** [comment] 2019-04-22 08:45
> Under what conditions though are you seeing an error?

The conditions are the same as mentioned in the AskUbuntu website.

**Comment by b-zee** [comment] 2019-08-20 09:46
As the issue is really with `xdg-utils` I wanted to mention that a fix has been committed a while ago (March 2019) by XDG: https://gitlab.freedesktop.org/xdg/xdg-utils/commit/bfcefa162b1dcd6d62e193019969ff2f5ff331cf

It's now about waiting for them to release a new version of their packages containing the fix.

**Comment by joshuef** [comment] 2019-10-04 11:49
with auth moving out of the browser I'm closing this

**Closed by joshuef** 2019-10-04 11:49 UTC
Labels: bug, help wanted, wontfix
