### ISSUE TITLE
Address bar can become unresponsive

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_browser#194] opened 2017-09-30 11:52 UTC
Operation System: n/a
Beaker Version: 0.6.0

Minor UX glitch:

- Start SAFE Browser
- Login to account
- While login is proceeding, type a SAFE URL without the safe:// prefix, hit return *before* the tab has finished the login process. Call me impatient, go on :wink:
- This URL never loads, user can click, hit return etc but as it lacks the safe:// prefix the browser does nothing.
- as soon as you *edit* what's in the address bar the problem goes away and the prefix is applied

This seems to happen because if the user types into the address bar on a clean tab, the safe:// prefix is automatically even though it is not shown in the address bar until you hit return, but that this fails to happen if the tab is busy.

**Comment by joshuef** [comment] 2017-10-02 07:44
@theWebalyst this is most likely due to the way we're handling `safe` interactions at the moment (as it's occurring as you login).

Current interactions occur in the main electron thread, which we're discovering is _bad_ practice. It causes a lot of hangs etc. We're aware of this and have some ideas to tackle which we'll be implementing _soon_.

So I'd hope that would address this. I'm going to leave this open to track it once we've got that nailed down.

**Comment by bochaco** [comment] 2018-08-07 17:50
Verify if this is also an issue in Peruse v0.6.0, otherwise let's close it as we won't be maintaining beaker.

**Comment by hunterlester** [comment] 2018-08-08 15:12
No longer an issue following the steps to reproduce with `peruse` branch of this repo.

**Closed by hunterlester** 2018-08-08 15:12 UTC
Labels: bug
