### ISSUE TITLE
Page disappears from history.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#604] opened 2019-02-20 16:30 UTC
**Steps to reproduce:**
1. Open SAFE browser and navigate through a few pages. Eg 1 > 2 > 3. History reads 1,2,3
2. Click back on browser. 3 > 2. History still reads 1,2,3
3. Click on a different page 2 > 4

**Expected result:**
History contains all pages visited in browsing session (1,2,3,4)
**Actual result:**
History does not list page user clicked back from (1,2,4)
[Browser history issue.pdf](https://github.com/maidsafe/safe_browser/files/2885607/Browser.history.issue.pdf)

**Comment by joshuef** [comment] 2019-02-20 16:55
closing as duplicate of #461 

Related to #557

**Closed by joshuef** 2019-02-20 16:55 UTC
Labels: bug

**Comment by calumcraig** [comment] 2019-02-21 09:04
Moving to done as story already exists for this issue (duplicate report here).
