### ISSUE TITLE
"Open Location" should point the cursor to the address bar - not working.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#600] opened 2019-02-20 10:11 UTC
From regression checklist:
"Open Location should point the cursor to the address bar?"
- Is not working, when click on this menu option nothing happens - focus does not move to the address bar as expected.
- CTRL + L shortcut also does not work.

**Comment by joshuef** [comment] 2019-02-20 11:00
Ah dang. This is caused by local scoping in https://github.com/maidsafe/safe_browser/commit/d54dbbb48b0b2f5224cd0c339bd9018b82f23931

Seems like we cannot use that. I'll revert this commit, and we can reopen the relevant issue and see how else we can handle this.

**Comment by joshuef** [comment] 2019-02-20 11:08
@manavbp will you pick this up. I think we can keep some of the other tweaks you made here, and just:

- [ ] Remove local scopiong for the UI actions
- [ ] Require a windowId be passed for the menu opening / closing.

The latter may require either a `windows` array in the UI store (which could then have an option for 'settingsMenuVisible'.

We'd then just need to pass this down as appropriate to ButtonsRHS, where it can be used as it is now.

**Closed** 2019-02-21 11:07 UTC
Labels: 0.11.2-RC2, bug

**Comment by safesurfer** [comment] 2019-02-25 09:41
QA Verified
