### ISSUE TITLE
AppImage file is not executable on linux

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#984] opened 2019-09-23 13:00 UTC
I'm not able to install the AppImage file. It doesn't show any apps to open this file and getting the following warning.
![image](https://user-images.githubusercontent.com/27578024/65427675-77ba3800-de30-11e9-9cd1-beaddda1a2e3.png)

PS: I've built AppImages locally for both safe-browser and safe-network-app. I'm able to open safe-network-app by double clicking it, whereas it is not possible with safe-browser appImage.

**Comment by joshuef** [comment] 2019-09-23 14:58
I'm not able to reproduce this. AppImage can be fine.

**Comment by b-zee** [comment] 2019-09-24 07:26
@safesurfer Did you download that file from releases? If so, then did you make the file executable (`chmod +x`)?

**Comment by joshuef** [comment] 2019-10-11 09:43
Markign this as wontfix, we can consider it a limitation for now.

**Closed by joshuef** 2019-10-11 09:43 UTC
Labels: wontfix

**Comment by veritas1** [comment] 2019-12-03 17:04
I experienced this issue on PopOS 19.04.

Executing the .AppImage from the command line gave the following error:

```
[main 16:41:08.180] › >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[main 16:41:08.184] › whoops! there was an uncaught error:
[main 16:41:08.184] › In the main process
[main 16:41:08.184] › {"message":"libssl.so.1.0.0: cannot open shared object file: No such file or directory","name":"Error"}
[main 16:41:08.185] › >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```
Installing libssl.so.1.0.0 resolved the issue.
