### ISSUE TITLE
Clearnet redirect message persists in new SAFE browser window

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#608] opened 2019-02-22 10:22 UTC
**Steps to reproduce:**
1. Launch SAFE Browser and navigate to a page with clearnet links.
2. Click on a CN link, SAFE Browser redirects:
![image](https://user-images.githubusercontent.com/44327924/53236327-f0cf9200-368b-11e9-9421-6e5a3bf83b4e.png)
3. Dismiss redirect message in SAFE browser and continue browsing.
![image](https://user-images.githubusercontent.com/44327924/53236386-0ba20680-368c-11e9-9dc5-c8f4490d3da5.png)
4. Open new SAFE browser window by CTRL + N or File menu option.

**Expected:**
New SAFE browser window opens with no messages.
**Actual:**
New SAFE browser window displays redirect message dismissed at step 3) above:
![image](https://user-images.githubusercontent.com/44327924/53236501-4d32b180-368c-11e9-83c2-98a0a7a7562b.png)

**Comment by joshuef** [comment] 2019-02-26 17:32
A dupe of #517 should be handled there.

**Closed by joshuef** 2019-02-26 17:32 UTC
Labels: bug
