### ISSUE TITLE
SAFE Browser hangs, Win 10

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe_browser#159] opened 2017-09-09 11:47 UTC
Operating System: Win10
Beaker Version: 0.5.1
Safe browser hangs when trying to navigate to a site in Windows.

To reproduce:
Start browser and login
Navigate to a site, e.g. safeblues.jpl

It does not hang in Linux

**Comment by hunterlester** [comment] 2017-09-09 16:11
Thank you for reporting. I'm experiencing the same. Wondering if this is potentially connected to our other problem of not being able to connect an authorised application we are also experiencing only on Windows.

**Comment by hunterlester** [comment] 2017-09-15 15:53
@SalvorinFex Hi Kurt, is this occurring when navigating to most user sites? Just `safe://safeblues.jpl`?

If you have the time (I don't take it lightly), would you please take note of the time when the freezing occurs and send me your corresponding browser logs?

Thank you.

**Comment by SalvorinFex** [comment] 2017-09-15 19:50
This is from yesterday when I think the issue presented itself.

[SAFE_Browser.MaidSafe-1505430628.txt](https://github.com/maidsafe/safe_browser/files/1307620/SAFE_Browser.MaidSafe-1505430628.txt)

**Comment by SalvorinFex** [comment] 2017-09-15 19:53
Today it seems to be working and the Win 10 protocol pop-up isn't asking for an App to open `safe://` like it did yesterday.

**Comment by bochaco** [comment] 2017-12-11 17:49
I just tried to open `safe://safeblues.jpl` on Alpha-2 but it doesn't exist. I'll be closing this issue now but please re-open it if you still can reproduce it with any other site and provide information for it. Thanks a lot @SalvorinFex .

**Closed by bochaco** 2017-12-11 17:49 UTC
