### ISSUE TITLE
Warnings about Hash history and react-warning-keys

### ISSUE THREAD

**Issue by Folatt** [maidsafe/safe_browser#396] opened 2018-10-10 09:17 UTC
This is what I see in the console, directly after starting the browser:

```
bundle.js:66711 Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack
warning @ bundle.js:66711
bundle.js:65110  action @@router/LOCATION_CHANGE @ 11:15:01.005
bundle.js:7214 Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in div
    in form
    in div
    in div
    in div
    in div
    in div
    in div
    in Login (created by Connect(Login))
    in Connect(Login) (created by Route)
    in Route (created by withRouter(Connect(Login)))
    in withRouter(Connect(Login)) (created by Route)
    in Route
    in Switch
    in div
    in div
    in div
    in App (created by Connect(App))
    in Connect(App) (created by Route)
    in Route (created by withRouter(Connect(App)))
    in withRouter(Connect(App))
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Connect(ConnectedRouter))
    in Connect(ConnectedRouter)
    in Provider
printWarning @ bundle.js:7214
DevTools failed to parse SourceMap: safe-auth://home/opt/Maidsafe/Peruse/resources/app.asar/webPreload.js.map
DevTools failed to parse SourceMap: safe-auth://home/opt/Maidsafe/Peruse/resources/app.asar/node_modules/performance-now/lib/performance-now.js.map
DevTools failed to parse SourceMap: safe-auth://home/opt/Maidsafe/Peruse/resources/app.asar/node_modules/auth-header/dist/util.js.map
DevTools failed to parse SourceMap: safe-auth://home/opt/Maidsafe/Peruse/resources/app.asar/node_modules/auth-header/dist/parse.js.map
DevTools failed to parse SourceMap: safe-auth://home/opt/Maidsafe/Peruse/resources/app.asar/node_modules/auth-header/dist/format.js.map
```

**Comment by hunterlester** [comment] 2018-10-10 14:32
Thank you for opening an issue, @Folatt 

I'm closing this one as a duplicate of https://github.com/maidsafe/safe_browser/issues/330

**Closed by hunterlester** 2018-10-10 14:32 UTC

**Comment by bochaco** [comment] 2018-10-12 14:12
Duplicate of #330
